import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import React from "react";
import { MonitorSmartphone, ShoppingCart } from "lucide-react";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className={`flex flex-col justify-between min-h-screen`}>
          <header
            className={`fixed flex justify-between items-center shadow-xl bg-white px-20 w-full z-10 h-20`}
          >
            <div className={`flex items-center gap-3`}>
              <MonitorSmartphone />
              <Link href="/" className={`font-bold text-2xl`}>
                Digital Shop
              </Link>
            </div>
            <div>
              <ShoppingCart />
            </div>
          </header>
          <div className={`w-[90%] mx-auto mt-28`}>{children}</div>
        </main>
      </body>
    </html>
  );
}
